version: 2.1

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    git config --global --add safe.directory /tmp/_circleci_local_build_repo
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

jobs:
  build:
    description: Trigger downstream CI/CD
    docker:
      - image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
    steps:
      - *localCheckout
      - run:
          name: Trigger GitHub actions in cicd-playground-downstream
          command: sh hello_world.sh
            #echo "Hello, Spencer!"
            #command: echo "Hello, Spencer!"
            #command: |2
            #curl --silent \
            #--write-out "\n%{response_code}\n" \
            #--request POST \
            #--header "Accept: application/vnd.github+json" \
            #--header "Authorization: Bearer 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" \
            #--header "X-GitHub-Api-Version: 2022-11-28" \
            #--data '{"event_type":"liboqs-upstream-test"}' \
            #https://api.github.com/repos/SWilson4/cicd-playground-downstream/dispatches   
