name: Release tests

on:
  release:
    types: [published]

jobs:
  downstream-release-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream
        run: |
          curl --silent \
               --write-out "\n%{response_code}\n" \
               --request POST \
               --header "Accept: application/vnd.github+json" \
               --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               --data '{ "event_type": "liboqs-release", "client_payload": { "tag": "${{ github.event.release.tag_name }}" } }' \
               https://api.github.com/repos/swilson4/cicd-playground-downstream/dispatches | tee curl_out \
            && grep -q "204" curl_out
